spring:
  application:
    name: dbDemo
  datasource:
    url: jdbc:postgresql://${DATABASE_URI:localhost}:5432/dbDemo?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml